### ISSUE TITLE
Update to be compatible with elm-test 4.x

### ISSUE THREAD

**Issue by mdevlamynck** [soenkehahn/elm-operational-mocks#1]
Can you update the elm-package.json to allow using elm-test 4.x? It should be compatible without any change to your code, so you can keep compatibility with elm-test 3.x.

**Comment by soenkehahn** [comment]
Unfortunately it's a bit more complicated. The test-suite uses parts of the `elm-test@3.1.0` api that are different in `elm-test@4.2.0`. I've created a PR that updates the library to work with the newest version of `elm-test`: #2. I think the library itself would work with older versions of `elm-test`, but I'm not really inclined to support dependency versions for which you cannot run the test-suite anymore.

So this would drop support for older versions of `elm-test`. Personally I'm not really against this, since elm tools lock down dependency versions, and people can still use the older version if they want to. @mdevlamynck: What do you think?

**Comment by mdevlamynck** [comment]
That's totally fine by me. I just suggested keeping compatibility for the sake of not wanting to impose anything on you (for instance I think dropping 3.x support implies new major version right?).

**Comment by soenkehahn** [comment]
I'm not sure. `elm-package diff` says it'd be just a patch level version bump. But I don't know if it takes dependency version changes into account. And I don't know whether they require a major bump.

**Comment by soenkehahn** [comment]
I can't find any mention of a requirement for a major bump here: https://github.com/elm-lang/elm-package#elm-package

**Comment by soenkehahn** [comment]
If you don't object I'll be releasing this as `4.0.1`.

**Comment by mdevlamynck** [comment]
That'd be awesome, thanks!

**Comment by soenkehahn** [comment]
Released as `4.0.1`. Thanks for the report.
